### ISSUE TITLE
Can you add support for spi nor flash chip？

### ISSUE THREAD

**Issue by jiuweiljp** [bbogush/nand_programmer#12]
In the project https://github.com/dword1511/stm32-vserprog (libcopencm3) use STM32F103C8T6 PA4,5,6,7 to support spi nor flash

**Comment by jiuweiljp** [comment]
old project https://github.com/dword1511/serprog-stm32vcp

**Comment by bbogush** [comment]
Hi,
Thank you for idea. It is possible, but currently SPI pins are not routed. So this requires redesign of PCB. I will add it to work backlog but not sure it can be done soon.

Regards

**Comment by jiuweiljp** [comment]
Thx, this would be really cool

**Comment by jiuweiljp** [comment]
Thx, this would be really cool

**Comment by alexgrach** [comment]
It would be nice to have I2C EEPROM support too...

**Comment by bbogush** [comment]
Closing issue. SPI support added in version 3.4.0. I2C support may be added in next releases.
