### ISSUE TITLE
Can show Effective(available) com port and put port select and connect  at  main window?

### ISSUE THREAD

**Issue by kuangjunchaos** [bbogush/nand_programmer#13]
Can show Effective(available) com port and put port select and connect  at  main window?

port select         buttom
Com60 |             connect!
            V

**Comment by bbogush** [comment]
Thank for idea, but I don't want to overload main window with multiple settings. This is not user friendly. The serial port should be configured once and usually it should be the same on the next connection. Currently settings are not saved but when this will be implemented selection of port should not be a problem.
