### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by alexgrach** [bbogush/nand_programmer#14]
It would be nice to have reset button. I have to use a wire to reset before flashing over SWD by st-link.

**Comment by bbogush** [comment]
HW reset button is rarely used and can be replaced by cable unplug-plug action. Thereby I would not add additional component to PCB design which may increase its size.

**Comment by alexgrach** [comment]
I've added NRTS just like BOOT0 and made some changes in schematics to make it look better and readable.
![nand_programmator](https://user-images.githubusercontent.com/7253483/95388868-a2701500-08fb-11eb-8e61-d509d5db0b35.png)
[nand_programmator.zip](https://github.com/bbogush/nand_programmer/files/5343890/nand_programmator.zip)
