### ISSUE TITLE
Can you add support for STM32F103ZET6

### ISSUE THREAD

**Issue by mlpzaq9998** [bbogush/nand_programmer#23]
[1、STM32F103ZE核心板--原理图-1807M.pdf](https://github.com/bbogush/nand_programmer/files/5648222/1.STM32F103ZE.--.-1807M.pdf)

**Comment by mlpzaq9998** [comment]
![IMG_0635](https://user-images.githubusercontent.com/6046642/101270620-a3b3a600-37b5-11eb-9592-7cbf1b806428.JPG)

Run NANDO to display the （112）wrong data length

**Comment by mlpzaq9998** [comment]
![Z664XETYEUMAQQ2X`XK8)6H](https://user-images.githubusercontent.com/6046642/101270691-71567880-37b6-11eb-81fd-eacb271a48f2.png)

**Comment by bbogush** [comment]
Hello,

I see STM32F103ZET6 should be compatible with NANDO's STM32F103VCT6. 
Regarding error, the version of firmware was read correctly so USB communication works. The reason of error is that NANDO  firmware received not enough or to many data in configuration command. The UART log can show more information. Are you using released firmware and PC program provided in GoogleDriver?

**Comment by mlpzaq9998** [comment]
using released PC program provided in GoogleDriver，The firmware is GitHub
How to eliminate errors?

**Comment by bbogush** [comment]
The firmware and PC program should be the same version because communication protocol sometimes changes. So you should use the released PC program and firmware from google driver or checkout git tag of the same version, i.e, git checkout 3.3.0.

**Comment by mlpzaq9998** [comment]
Use the same version of the checkout git tag，NANDO display

Info: Connected to programmer
Info: Firmware version: 3.3.0
Info: Detecting chip ...
Info: ID 0x8F 0x8F 0x8F 0x8F 0x8F
Info: Chip not found in database
Info: Detecting chip ...
Info: ID 0x8F 0x8F 0x8F 0x8F 0x8F
Info: Chip not found in database

It should be a hardware problem

**Comment by mlpzaq9998** [comment]
Can the new firmware include HEX

**Comment by bbogush** [comment]
0x8F 0x8F 0x8F 0x8F 0x8F pattern shows hardware problem - unconnected pins or high stray capacitance.
  
Yes, hex will be included, also it can be received by following conversion, but haven't tried if it works.
../../compiler/gcc-arm-none-eabi-4_9-2015q1/bin/arm-none-eabi-objcopy --input-target=binary --output-target=ihex obj/fw.bin obj/fw.hex

**Comment by bbogush** [comment]
Closing old issues. Please reopen if you still have questions.
