### ISSUE TITLE
is it support BGA packaged nand?

### ISSUE THREAD

**Issue by youxiaojie** [bbogush/nand_programmer#3]
is it support BGA packaged nand?

**Comment by bbogush** [comment]
The panel for BGA is not available yet.

**Comment by Blue-PCB** [comment]
Any ETA or update on the BGA panel?

I was hoping for a FBGA156 panel to examine an eMMC. 

The BeeProg2 programmer BGA153 adapter are $625 USD... just for the adapter :-1:
https://www.elnec.com/en/products/programming-adapters/DIL48_BGA153-1_01_ZIF_eMMC-3/

Cheers
