### ISSUE TITLE
NAND128-A/NAND256-A/NAND512-A/NAND01G-A: unsupported read command style

### ISSUE THREAD

**Issue by ghost** [bbogush/nand_programmer#31]
There is a series of very old NAND from STMicroelectronics:
![image](https://user-images.githubusercontent.com/73182853/108871809-84176700-75c7-11eb-81e3-88397ebbd0fc.png)
Datasheet: https://datasheetspdf.com/datasheet/NAND128-A.html

The problem we have here is that they use 2 different commands for reading 2 different halves of a page, so with the current software setup, we can only really read the 1st half of the page. Adding support for these chips will require additional work on the firmware and the Qt host application.
![image](https://user-images.githubusercontent.com/73182853/108872034-c476e500-75c7-11eb-8dba-bcfb5b2f794d.png)

Do you think it's worth the time making changes to the fw and host application to add support for these chips, or should we file these off as "impossible to support" for now?

**Comment by bbogush** [comment]
Hello,
From what I understand the pointer can set to area A and read operation will read whole page including spare. So it should as others chips.
![image](https://user-images.githubusercontent.com/12390301/108882753-6a990e00-760d-11eb-9174-79d079cb2a16.png)

**Comment by nQ1PX** [comment]
Oh, guess I didn't understand the datasheet very well then. I will try it with my chip and report back.
