### ISSUE TITLE
Potential issues on bad block handling

### ISSUE THREAD

**Issue by nQ1PX** [bbogush/nand_programmer#32]
I was testing a few chips I happened to have on hand and preparing to send in a PR, but I noticed the current bad block handling strategy might not be the best here. Suppose I have a 128MB chip with 4 bad blocks, the read result does not correlate to the actual data on flash, as I have 0x80000 of 0x00 at the very end of the buffer.

![image](https://user-images.githubusercontent.com/73182853/108912001-03239400-75f6-11eb-9c83-178db563b51e.png)

And if I load a 128MB file, the write operation will cause the program to error out too, because my file was "too large" if you subtract the 4 bad blocks.
![image](https://user-images.githubusercontent.com/73182853/108909317-66abc280-75f2-11eb-94ee-c1011b255a80.png)

Usually the "skip bad block" option in other things I've seen just increments the counter and skips the actual r/w operation, so fill bad blocks with FF in buffer for read and skipping writing/erasing entirely (discard data for bad blocks). This way we can still have a consistent, whole 128MB file without having to worry about manually recording the offsets and mangling with the binary with a hex editor to insert/remove blank bits.

**Comment by bbogush** [comment]
Fixed. Skipped bad block are not included in read buffer.
