### ISSUE TITLE
Add support for K9G8G08U0M

### ISSUE THREAD

**Issue by donnm** [bbogush/nand_programmer#33]
Thank you for this project! I used the definition for K9G8G08U0A as a template for K9G8G08U0M which has a different ID:

K9G8G08U0M, 2048, 262144, 1073741824, 64, 0, 20, 12, 12, 10, 10, 12, 12, 12, 5, 5, 5, 25, 25, 20, 3, 2, 0, 48, -, 144, 255, 128, 16, 96, 208, 112, 236, 211, 20, 37, 100

Tested and confirmed working.

**Comment by bbogush** [comment]
Thanks for reporting. I've adjusted a bit timing parameters according to datasheet  (tCLS etc) and added to list of supported chips.
