### ISSUE TITLE
Parallel NOR flash support?

### ISSUE THREAD

**Issue by donnm** [bbogush/nand_programmer#37]
I started adding support for M29W640GB in the chip database before realising it was NOR flash (couldn't find all the timing info in the datasheet). Does this have any chance of working?

**Comment by bbogush** [comment]
Currently NOR is not supported, I think it will not work because NOR uses different programming approach.

**Comment by gitercn** [comment]
I'm also looking for a programmer for Spansion S29 NOR FLASH programmer (TSOP56). Is there any open source NOR programmers? Could this project add NOR support?

**Comment by bbogush** [comment]
> I'm also looking for a programmer for Spansion S29 NOR FLASH programmer (TSOP56). Is there any open source NOR programmers? Could this project add NOR support?

I haven't seen open source NOR programmers. This project can be extended to support NOR and STM chip has support of it. I'm not sure when it will be added because development requires some time.

**Comment by donnm** [comment]
There's this, an Arduino Mega connected to a 32 pin PDIP NOR flash: https://mint64.home.blog/2018/07/29/parallel-nor-flash-eeprom-programmer-using-an-arduino-part-1-the-sst39sf040-and-planning/

Part 2 has the Arduino sketch code: https://mint64.home.blog/2018/07/30/parallel-nor-flash-eeprom-programmer-using-an-arduino-part-2-arduino-code-and-serial-comms/
