### ISSUE TITLE
TSOP56 NAND Compatibility

### ISSUE THREAD

**Issue by kooroshi60** [bbogush/nand_programmer#40]
Does NANDO support 56 pin NAND memories? If so, how is the pin assignment on the 48pin socket ?
I would be happy to design and share the PCB for such an adapter if it is possible.

**Comment by bbogush** [comment]
TSOP-56 is usually used by NOR memories. I've checked few websites with parts and haven't found 56 pin NAND. NOR currently is not supported because it requires change of MCU to another model with more pins.

**Comment by kooroshi60** [comment]
Thank you so much for your informative answer.
