### ISSUE TITLE
Operation address exceeded chip size

### ISSUE THREAD

**Issue by hpo14** [bbogush/nand_programmer#43]
backup.bin: Backup with nando, 268435456 Bytes (256MB)
Chip1 and Chip2: MX30LF2G18AC, (256MB)

Below logs:
1. Write backup.bin to chip1 --> success
2. Write backup.bin to chip2 --> Error: "Programmer sent error: (100) Operation address exceeded chip size"

The error happened sometimes but should less than 10% from my observation.

log of Chip 1:
```Info: Detecting chip ...
Info: ID 0xc2 0xda 0x90 0x95 0x06
Info: Writing data ...
Info: Data has been successfully written
```

log of Chip 2:
```Info: Detecting chip ...
Info: ID 0xc2 0xda 0x90 0x95 0x06
Info: Writing data ...
Info: "Skipped bad block at 0x0fb20000 size 0x00020000"
Info: "Skipped bad block at 0x0fca0000 size 0x00020000"
Error: "Programmer sent error: (100) Operation address exceeded chip size"
```

**Comment by bbogush** [comment]
The error is shown because bad blocks are skipped and available flash size is less then file size. Probably flash backup does not contain useful data at the end so the file can be trimmed by few blocks.
