### ISSUE TITLE
Wrong timing calculation code?

### ISSUE THREAD

**Issue by 7134956** [bbogush/nand_programmer#47]
https://github.com/bbogush/nand_programmer/blob/7f0379c779699122d7c1a9685d2fd52b0a425df7/qt/parallel_chip_info.cpp#L56
https://github.com/bbogush/nand_programmer/blob/7f0379c779699122d7c1a9685d2fd52b0a425df7/qt/parallel_chip_info.cpp#L59
https://github.com/bbogush/nand_programmer/blob/7f0379c779699122d7c1a9685d2fd52b0a425df7/qt/parallel_chip_info.cpp#L64
https://github.com/bbogush/nand_programmer/blob/7f0379c779699122d7c1a9685d2fd52b0a425df7/qt/parallel_chip_info.cpp#L83
This does not match the appnote.
tCH or tCS.

https://github.com/bbogush/nand_programmer/blob/7f0379c779699122d7c1a9685d2fd52b0a425df7/qt/parallel_chip_info.cpp#L72
waitSetupTime = std::max(params[CHIP_PARAM_T_WP], params[CHIP_PARAM_T_**RP**]); 

![image](https://user-images.githubusercontent.com/1007039/177166273-9f5e1847-0306-44af-a10d-dc424ef4c521.png)

This is how my samsung chips read fine:
https://github.com/7134956/nand_programmer/commit/6ec011dd5dfe07d47d72442f6874e349159a63fc

**Comment by bbogush** [comment]
Good catch. Thank you!
