### ISSUE TITLE
Does it support GD32F103VCT6?

### ISSUE THREAD

**Issue by myseil** [bbogush/nand_programmer#53]
Hi！
I have a GD32F103VCT6 chip, can use it to replace STM32F103VCT6?

**Comment by myseil** [comment]
GD32F103VCT6 is determined to be available and can replace STM32F103VCT6

**Comment by myseil** [comment]
![](https://cdn.jsdelivr.net/gh/myseil/PicGoCDN@master/img/20221218144837.png)
I'm sorry! Using GD32F103VCT6 does not work properly, and the data written is not consistent. I don't know where this is the problem! Attached is the [GD32F103VCT6 datasheet](https://cdn.jsdelivr.net/gh/myseil/PicGoCDN@master/img/GD32F103xxDatasheet_Rev2.12.pdf)

**Comment by myseil** [comment]
The main frequency of GD32F103VCT6 is higher than that of STM32F103VCT6, is this the reason?

**Comment by alexgrach** [comment]
GD32F303VCT6 is used intead of STM32F103VCT6 in 3d printer boards

**Comment by myseil** [comment]
> GD32F303VCT6 is used intead of STM32F103VCT6 in 3d printer boards

？？？

**Comment by ssp97** [comment]
https://oshwhub.com/myseil/nandopen
In this article, it is proven that GD32F103 is binary compatible with STM32F103.

**Comment by myseil** [comment]
> 

This project was created by me and can not be used with GD32!

**Comment by ssp97** [comment]
> > 
> 
> This project was created by me and can not be used with GD32!

Yes. I saw in your article that it was written, "The program can be directly flashed following the original author's steps, just by replacing the STM tools with GD tools, it's quite simple."(程序按照原作者的步骤直接刷，就是STM的工具换成GD的工具，很简单) That's why I believed that running it on GD32 has already been achieved.

**Comment by myseil** [comment]
> 

emmm！立创的这个项目也是我搬过去的，也是用的GD工具刷的，然后和STM的进行对比验证，会发现数据不一致！

**Comment by bbogush** [comment]
GD32 is not supported. Closing issue.
