### ISSUE TITLE
K9K2G08U0M SLC Die Stack series support

### ISSUE THREAD

**Issue by loki-amorf** [bbogush/nand_programmer#60]
Is any big difference in work logic between K9K2G08U0M and K9F2G08U0B for example?

My quick research third symbol meaning
F : SLC Normal
K : SLC Die Stack
some of SLC Die Stack chips have 2 chip enable pin CE0/CE1 and CE0 but K9K2G08U0M has only one CE

**Comment by bbogush** [comment]
No big difference, maybe some timing parameters. K9K2G08U0M is 1.8V which is currently not supported.
