### ISSUE TITLE
Hangs 3.5.0

### ISSUE THREAD

**Issue by Sana956** [bbogush/nand_programmer#63]
Ver.  3.5.0
Hangs when writing on the second BB.

(Info: "Bad block at 0x0035a840 size 0x00021000"
Info: "Bad block at 0x0035b080 size 0x00021000")
K9F1G8U0E

Doesn't work either - "Read bad blocks":
(Error: "Programmer sent error: (104) Failed to read chip")

Everything else works.
Windows 10 64x

**Comment by bbogush** [comment]
Thanks for trying new firmware. I cannot reproduce reported issue on my board. Error 104 is reported when there is hardware communication problem between STM and NAND. Bad block on write also points to this.

**Comment by v6760hu** [comment]
可以弄个GD32F103VCT6 的固件吗  STM32F103VCT6  快
