### ISSUE TITLE
可以弄个GD32F103VCT6 的固件吗 STM32F103VCT6 快

### ISSUE THREAD

**Issue by v6760hu** [bbogush/nand_programmer#64]
主频也比 STM32F103VCT6 高  而且还提升了写入速度

**Comment by bbogush** [comment]
Thanks for idea! Looks GD32F103VCT6 is good low price alternative. Unfortunately developing new board and adding support is big effort even if they looks similar. No plans for this now.

**Comment by v6760hu** [comment]
stm32f407vet




?凡事↗都飞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bbogush/nand_programmer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 凌晨4:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bbogush/nand_programmer] 可以弄个GD32F103VCT6 的固件吗 STM32F103VCT6 快 (Issue #64)





 
Thanks for idea! Looks GD32F103VCT6 is good low price alternative. Unfortunately developing new board and adding support is big effort even if they looks similar. No plans for this now.
